### ISSUE TITLE
max number of stocks or forex pairs before ticker starts again 

### ISSUE THREAD

**Issue by sainiaj** [lavolp3/MMM-AVStock#13]
Hi how can i increase the max numbers of forex pairs to show up under ticker mode

Currently it shows total of 19 regardless what speed duration i select currently set to 60

**Comment by sainiaj** [comment]
"AUDCAD","AUDCHF","AUDJPY","AUDNZD","AUDUSD","BGNRON","CADCHF","CADJPY","CHFBGN","CHFJPY","CHFRON","CHFTRY","EURAUD","EURCAD","EURCHF","EURCZK","EURDKK","EURGBP","EURHKD","EURHUF","EURILS","EURJPY","EURMXN","EURNOK","EURNZD","EURPLN","EURRON","EURRUB","EURSEK","EURSGD","EURTRY","EURUSD","EURZAR","GBPAUD","GBPBGN","GBPCAD","GBPCHF","GBPCZK","GBPDKK","GBPHKD","GBPHUF","GBPJPY","GBPNOK","GBPNZD","GBPPLN","GBPRON","GBPSEK","GBPSGD","GBPTRY","GBPUSD","GBPZAR","HKDJPY","NZDCAD","NZDCHF","NZDJPY","NZDUSD","SGDHKD","SGDJPY","TRYBGN","TRYJPY","TRYRON","USDBGN","USDCAD","USDCHF","USDCZK","USDDKK","USDHKD","USDHUF","USDILS","USDJPY","USDMXN","USDNOK","USDPLN","USDRON","USDRUB","USDSEK","USDSGD","USDTRY","USDZAR"


My current symbols and alias. This is the max forex pairs i would be lowering it to 29 but will add few commodities which i also trade.

It's weird its only showing first 19 and the restarts the loop regardless of duration set to 60 seconds or 600 seconds

**Comment by eouia** [comment]
I'll inspect but till Monday I have no time to do that. plz wait a while.

**Comment by eouia** [comment]
Hmm.. It's too wide to calculate the virtual width of the whole ticker line. Sorry, I cannot imagine too many stocks could be displayed like your case.
Different approach would be needed for ticker mode to handle this kind of large amounts. sorry.

**Comment by popeye2002** [comment]
Hello, I'm very new at MM2 and so far I really like this module with the same exception as above.  I track about 50 different symbols and they don't display in the ticker mode.  I can see them in table view but that takes up my entire mirror!  I'd really like to see the ticker allow unlimited or at least many more stock symbols.

**Comment by eouia** [comment]
Sorry, At this moment, I have no idea about how can show huge amount of tables. Maybe in next updates I'll consider.

**Comment by popeye2002** [comment]
Thank you for the reply.I really like the MMM-AVStock module and hope someone will come along and provide a solution.
Scott Brown "Life is Good" 

    On Monday, April 27, 2020, 12:25:21 AM PDT, Seongnoh Sean Yi <notifications@github.com> wrote:  
 
 


Sorry, At this moment, I have no idea about how can show huge amount of tables. Maybe in next updates I'll consider.

**Comment by lavolp3** [comment]
I'll have a look at it over the coming days/weeks. Sorry other projects need to be finished

**Comment by lavolp3** [comment]
I have looked into this again while doing the major update to v2.0.0.
The problem seemingly is that the max width of the ticker or its container is limited. That limits the runway of the ticker to the left. It starts again without running through all ticker items because it can't run further to the left.
With the current version you'll still not be able to use more than 10-20 tickers, but I'll try to find a workaround.

**Comment by lavolp3** [comment]
I believe the newest update has fixed this It should now be possible to have much more stocks in the ticker.
Can you please check @popeye2002 @sainiaj ?

However, keep in mind that the api is limited to 500 calls per day, giving a span of 3 minutes between ever call.
It would therefore take an hour to even call twenty different items, not to mention the optional tech calls (sma, ema...)

Currently it's not such a big problem, since data is one day old nevertheless.
