### ISSUE TITLE
Not Displaying

### ISSUE THREAD

**Issue by Boastful1353** [lavolp3/MMM-AVStock#6]
The module will not display even with the default basic settings. I added my API key and used the exact config lines from the readme.

**Comment by eouia** [comment]
I need a log to examine what happened. If you can, post/send your back-end/front-end log. (You can get both with `npm start dev`)

**Comment by jprucks** [comment]
Hey, I likely had the same issue. You're missing some commas in the javascript file in the T/F portion of the config default section. I don't know much about coding but adding those two commas fixed the issue. The error was something to the effect of "the config file has been improperly configured." The issue was actually in the main program file.

**Comment by lavolp3** [comment]
@jprucks  Good find! The added config options in the detailed config in the Readme are missing some commas. Will correct this.

**Comment by lavolp3** [comment]
Is fixed now. @marvinej 
Take care of the missing commas in the configs copied to the config.js file.
Or replace it with the new sample config in the README section
