### ISSUE TITLE
API broken again?

### ISSUE THREAD

**Issue by hermannw** [lavolp3/MMM-AVStock#64]
After making the changes mentioned in #62, everything worked. But since the last few days, it only shows an empty table. Is the API broken again?

**Comment by lavolp3** [comment]
Hello @hermannw I believe it was some changes in the API. Then changes from #62 neither worked for me.
I am now again trying to reprogram the module to use the yahoo finance API and have progressed a few steps again. Please stay tuned. 
In the meantime you can also reset your changes from #62 because I think the original code should work.

**Comment by thymon13** [comment]
Hello,

The API is working for me. However, I didn't understand how I can set up the API call. The free API allows for 100 calls per day.

Best regards,

**Comment by lavolp3** [comment]
You can request a free api key at 
https://www.alphavantage.co/support/#api-key
But as said, I am currently working again on a key-less api.
The Alphavantage API does not return any intraday values anymore for the free tier, only last day's close.

**Comment by lavolp3** [comment]
@hermannw @thymon13 please use the newest update and let me know if it works.
I have now integrated yahoo finance for complete and up-to-date data

**Comment by hermannw** [comment]
Sorry, I switched to a different module in the mean time.

**Comment by lavolp3** [comment]
Closed with update to yahoo finance API
